apache/calcite-avatica

- core/pom.xml
- site/develop/index.md
Protobuf compilation will still run by default, but users can disable it by providing `-P!compile-protobuf`.
> CALCITE-2073 Allow disabling of the maven-protobuf-plugin

- site/.gitignore
- site/Gemfile
- site/README.md
- site/_config.yml
- site/_docs/history.md
- site/_includes/news_contents.html
- site/_includes/news_item.html
- site/_layouts/news_item.html
- site/_posts/2016-03-03-separate-project.md
- site/_posts/2016-03-18-release-1.7.1.md
- site/_posts/2016-06-04-release-1.8.0.md
- site/_posts/2016-11-01-release-1.9.0.md
- site/_posts/2017-03-31-new-avatica-repository.md
- site/_posts/2017-05-30-release-1.10.0.md
- site/_posts/2018-03-09-release-1.11.0.md
- site/add-avatica-go-docs.sh
- site/develop/avatica.md
- site/develop/index.md
- site/docker-compose.yml
- site/downloads/avatica-go.md
- site/downloads/avatica.md
- site/index.html
- site/news/avatica-go-releases/index.html
- site/news/avatica-releases/index.html
- site/news/index.html
- site/news/releases/index.html
This PR updates the website in preparation for the release of Avatica-Go 3.0.0 later today.
Similar to https://github.com/apache/calcite/pull/677, I have added a docker-compose file to ease development of the website.
In terms of the website itself, I've reshuffled some of the content and added/updated some pages so that content from Avatica-Go fits properly.
`add-avatica-go-docs.sh` pulls in the avatica-go content by cloning the repository and copying the files to the appropriate locations under `site`. I tried using symlinks, but jekyll does not build them (I think this might be due to using Docker for Windows). The downside of pulling the content in is that it dirties the working tree when building the site. It's possible to do a `git reset` after pushing the website, and it's …
> [CALCITE-1937] Update the avatica website in preparation for avatica-go content

- docker/src/assembly/docker-files.xml
- site/_docs/howto.md
- site/downloads/avatica-go.md
- site/downloads/avatica.md
- src/main/config/assemblies/source-assembly.xml
This updates the website and maven configs to stop releasing zips for future releases.
The site was tested locally and works fine.
Can someone verify that I have updated the pom.xml files correctly?
> [CALCITE-2333] Stop releasing zips

- core/src/main/java/org/apache/calcite/avatica/remote/AbstractService.java
> Improve exception message in AbstractService

- core/src/main/java/org/apache/calcite/avatica/util/AbstractCursor.java
- core/src/test/java/org/apache/calcite/avatica/util/StructImplTest.java
1. Remove special treatment for struct types with one attribute in AbstractCursor#createAccessor.
2. Add parameterized unit test for testing struct accessors using multiple internal representations for struct types.
> [CALCITE-2776] Wrong value when accessing struct types with one attribute (Stamatis Zampetakis)

- pom.xml
To harmonize the versions of Jackson among the different projects.
> CALCITE-3179: Bump Jackson from 2.9.8 to 2.9.9

- core/src/main/java/org/apache/calcite/avatica/util/AbstractCursor.java
- core/src/test/java/org/apache/calcite/avatica/util/ArrayImplTest.java
Currently Calcite supports array columns from both ArrayImpl or List input.
It also supports both struct and plain java object data format.
The issue is that an exception is thrown when data is a list of plain java objects, while it works fine when data is a list of struct or an array of plain java objects.
I have created unit tests to demonstrate the bug.
Currently these unit tests pass: arraysOfStructs(), listOfStructs(), arrayOfJavaObjects() but listOfJavaObject() is failed.
Method org.apache.calcite.avatica.util.AbstractCursor.ArrayAccessor.convertValue() misses a case for Types.OTHER, which is for general java objects, hence the exception is thrown.
This pull request adds that missing type and makes all four unit tests pass. 
Reference link: …
> [CALCITE-4181] Fix exception when selecting List<Object>

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/6.8.1/release-notes.html
- Faster Kotlin DSL script compilation
- Vendor selection for Java toolchains
- Task execution in composite builds
- Consistent dependency resolution
> Bump Gradle 6.7 -> 6.8.1

- core/src/main/java/org/apache/calcite/avatica/ColumnMetaData.java
- core/src/main/java/org/apache/calcite/avatica/util/AbstractCursor.java
- server/src/test/java/org/apache/calcite/avatica/remote/RemoteMetaTest.java
* Add BigDecimal type to lookup hash
Change-Id: I39ca2008bc3cb344fafbd3a1b8a0d21994443083
> [CALCITE-4752] PreparedStatement#SetObject() fails for BigDecimal values

- core/src/main/java/org/apache/calcite/avatica/AvaticaUtils.java
- core/src/test/java/org/apache/calcite/avatica/test/AvaticaUtilsTest.java
I want make the exception information more explicit for instantiate plugin in this PR. such as when we want REATE SCHEMA or CREATE TABLE supported. and we do not add the class to the class path we got the exception as follows:
`Error: Error while executing SQL "CREATE TABLE t (i INTEGER, j VARCHAR(10))": Property 'org.apache.calcite.sql.parser.ddl.SqlDdlParserImpl#FACTORY' not valid for plugin type org.apache.calcite.sql.parser.SqlParserImplFactory (state=,code=0)`
would be great if we can make the error message more explicit , such as: 
`"Property 'org.apache.calcite.sql.parser.ddl.SqlDdlParserImpl#FACTORY' not valid as 'org.apache.calcite.sql.parser.ddl.SqlDdlParserImpl' not found in the classpath."  `
> [CALCITE-4877] Make the exception information more explicit for instantiate plugin.

- core/src/main/java/org/apache/calcite/avatica/remote/CommonsHttpClientPoolCache.java
- server/src/test/java/org/apache/calcite/avatica/AvaticaSpnegoTest.java
- server/src/test/java/org/apache/calcite/avatica/RemoteDriverTest.java
- server/src/test/java/org/apache/calcite/avatica/server/HttpServerSpnegoWithoutJaasTest.java
Before this change running the tests prints a lot of messages to
standard out cluttering useful output (testname, success, failure, etc.)
and slowing down the build.
1. Remove direct calls to System.out in tests; it is considered bad
practice in general.
2. Remove SPNEGO debug information by unsetting System properties; when
necessary the developer can set them explicitly. Debug info shouldn't
be always on especially on standard out.
3. Use loggers instead of System.out to print useful info in production
code.
> Silence standard out messages in tests

- build.gradle.kts
The doc title should be " Apache Calcite Avatica API", but is "Apache Calcite Avatica calcite-avatica API".
> Site: Change the javadoc title to Apache Calcite Avatica API

- core/src/main/java/org/apache/calcite/avatica/remote/ProtobufTranslationImpl.java
Add request/response type to the protobuf debug messages so that it's possible to debug and understand problems in the protocol with clients.
> [CALCITE-4962] Protobuf debug does not show request/response type

- .github/workflows/main.yml
- .github/workflows/publish-non-release-website-updates.yml
- .github/workflows/publish-site-and-javadocs-on-release.yml
- .travis.yml
- README.md
- build.gradle.kts
- docker/README.md
- site/README.md
- site/_config.yml
- site/_docs/compatibility.md
- site/_docs/index.md
- site/develop/avatica.md
- tck/README.md
This would need to happen in concert with changes to the Calcite repo.
Although I think perhaps the first (and lowest impact) change will be to the site repo.
**Note: This PR is merely to help with review. It should not be merged as it will eventually replace `master`**
> [CALCITE-4147] Rename "master" branch to "main"

- server/src/main/java/org/apache/calcite/avatica/jdbc/JdbcMeta.java
- server/src/test/java/org/apache/calcite/avatica/jdbc/JdbcMetaTest.java
NullPointerException when send ExectuteRequest via protobuf with no parameters
> [CALCITE-4900] NullPointerException when send ExectuteRequest via protobuf with no parameters

- gradle.properties
The PR to upgrade bouncycastle version to 1.70 (latest available)
> [CALCITE-5373] Upgrade bouncycastle to 1.70

- core/src/test/java/org/apache/calcite/avatica/util/DateTimeUtilsTest.java
The `DateTimeUtilsTest.testSqlDateToUnixDateWithCustomCalendar` test fails in the Europe/London time zone. The issue is due to the use of `TimeZone.setRawOffset(int)` which expects the provided value to be the offset from GMT, but the test provides the offset from UTC.
I tested the fix in several time zones and they all passed.
> [CALCITE-5494] Time zone tests in DateTimeUtilsTest should pass in Europe/London

- .github/workflows/main.yml
- build.gradle.kts
- gradle.properties
The idea is to use `jdk8.checkstyle.version` gradle property which will be used in case of java 8
for other java version `checstyle.version` will be used
This allows to compile Avatica with java 8 without explicitly set checkstyle version
also mentioned at https://lists.apache.org/thread/r27kdvvhr0222nqlog7xzn5y3yjvz6jp
> [CALCITE-6141] Add jdk8.checkstyle property, use jdk8.checkstyle in case of java 8

- site/_docs/index.md
Please review the initial integration of the Calcite CLI tool using Go in list of clients . If any adjustments are needed, kindly let me know. @F21
Thanks.
> Add Calcite CLI tool to list of Avatica Clients on website

- .gitignore
- .idea/vcs.xml
- .ratignore
This is almost a cherry-pick (link to GitHub changed to Avatica's repo) from Calcite to have links to JIRA/GitHub in IDEA and enable commit inspection enabled
> Apply same vcs.xml as for Calcite

- core/src/main/java/org/apache/calcite/avatica/util/AbstractCursor.java
- core/src/test/java/org/apache/calcite/avatica/util/TimeFromNumberAccessorTest.java
- core/src/test/java/org/apache/calcite/avatica/util/TimestampAccessorTest.java
- core/src/test/java/org/apache/calcite/avatica/util/TimestampFromNumberAccessorTest.java
- core/src/test/java/org/apache/calcite/avatica/util/TimestampFromUtilDateAccessorTest.java
> [CALCITE-6282] Avatica ignores time precision when returning TIME results

- build.gradle.kts
- gradle.properties
also add option to specify NVD API key
also add target to analyze depencies in all modules
> [CALCITE-6656] Update owasp plugin from 5.2.2 to 10.0.4 in Avatica

- bom/build.gradle.kts
- core/build.gradle.kts
- core/src/main/java/org/apache/calcite/avatica/AvaticaResultSet.java
- core/src/main/java/org/apache/calcite/avatica/AvaticaSite.java
- core/src/main/java/org/apache/calcite/avatica/ColumnMetaData.java
- core/src/main/java/org/apache/calcite/avatica/MetaImpl.java
- core/src/main/java/org/apache/calcite/avatica/util/AbstractCursor.java
- core/src/main/java/org/apache/calcite/avatica/util/Cursor.java
- core/src/test/java/org/apache/calcite/avatica/AvaticaResultSetConversionsTest.java
- core/src/test/java/org/apache/calcite/avatica/AvaticaResultSetThrowsSqlExceptionTest.java
- core/src/test/java/org/apache/calcite/avatica/CursorFactoryDeduceTest.java
- gradle.properties
- shaded/core/src/test/java/org/apache/calcite/avatica/shadetest/ShadingTest.java
- standalone-server/src/test/java/org/apache/calcite/avatica/shadetest/ShadingTest.java
For more details, refer jira: https://issues.apache.org/jira/browse/CALCITE-5094
> [CALCITE-5094] Calcite JDBC Adapter and Avatica should support MySQL UNSIGNED types of TINYINT, SMALLINT, INT, BIGINT
